language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # valgrind, for helgrind
  - sudo apt-get install -qq valgrind

script: 
  - qmake
  - make
  - valgrind --tool=helgrind --log-file=helgrind.log -v ./travis_qmake_gcc_cpp11_helgrind
  - cat helgrind.log
