language: cpp
compiler: gcc
dist: bionic

install: 
  # valgrind, for helgrind
  - sudo apt-get install -qq valgrind

script: 
  - qmake
  - make
  - valgrind --tool=helgrind --log-file=helgrind.log -v ./travis_qmake_gcc_cpp11_helgrind
  - cat helgrind.log
